# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/zyperformance',
                'doc_host': 'https://zysalice.github.io',
                'git_url': 'https://github.com/zysalice/zyperformance',
                'lib_path': 'zyperformance'},
  'syms': {'zyperformance.core': {'zyperformance.core.foo': ('core.html#foo', 'zyperformance/core.py')}}}
